# Generated by Django 5.1.1 on 2024-10-07 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('price', models.FloatField()),
                ('createdate', models.DateField(blank=True, null=True)),
                ('sold', models.BooleanField(default=False)),
                ('image', models.ImageField(default='uploads/item/noimage.png', upload_to='uploads/item/')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='members.profile')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.itemcondition')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.sport')),
            ],
        ),
    ]
